name: Build and Deploy HonKit to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can use Node.js 14 or higher

    - name: Install HonKit
      run: npm install -g honkit

    - name: Install HonKit Plugins
      run: honkit install

    - name: Build HonKit
      run: honkit build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
        publish_branch: gh-pages
